server:
  port: 80

spring:
  profiles:
    default: local
    group:
      local:
        - local
        - oauth2
        - jwt
        - swagger
        - codef
      prod:
        - prod
        - oauth2
        - jwt
        - swagger
        - codef