server:
  port: 8080

spring:
  datasource:
    url: "${spring_datasource_url}"
    username: "${spring_datasource_username}"
    password: "${spring_datasource_password}"
    driver-class-name: "${spring_datasource_driver-class-name}"
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  output:
    ansi:
      enabled: always
  mvc:
    pathmatch:
      matching-strategy: PATH_PATTERN_PARSER

logging:
  level:
    root: info

firebase:
  url: "${firebase_url}"

management:
  server:
    port: "${management_server_port}"
  endpoints:
    web:
      exposure:
        include: prometheus, health
  endpoint:
    health:
      show-details: never
  health:
    redis:
      enabled: true
    db:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true